package com.kk.pojo;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.aid
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.aname
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounts.acontent
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    private String acontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.aid
     *
     * @return the value of accounts.aid
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.aid
     *
     * @param aid the value for accounts.aid
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.aname
     *
     * @return the value of accounts.aname
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.aname
     *
     * @param aname the value for accounts.aname
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounts.acontent
     *
     * @return the value of accounts.acontent
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public String getAcontent() {
        return acontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounts.acontent
     *
     * @param acontent the value for accounts.acontent
     *
     * @mbggenerated Tue Jun 28 10:39:24 CST 2022
     */
    public void setAcontent(String acontent) {
        this.acontent = acontent == null ? null : acontent.trim();
    }

    @Override
    public String toString() {
        return "Account{" +
                "aid=" + aid +
                ", aname='" + aname + '\'' +
                ", acontent='" + acontent + '\'' +
                '}';
    }
}